#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : deprecated-urllib3
Version  : 1.24.1
Release  : 72
URL      : https://files.pythonhosted.org/packages/b1/53/37d82ab391393565f2f831b8eedbffd57db5a718216f82f1a8b4d381a1c1/urllib3-1.24.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/b1/53/37d82ab391393565f2f831b8eedbffd57db5a718216f82f1a8b4d381a1c1/urllib3-1.24.1.tar.gz
Summary  : HTTP library with thread-safe connection pooling, file post, and more.
Group    : Development/Tools
License  : MIT
Requires: deprecated-urllib3-license = %{version}-%{release}
Requires: deprecated-urllib3-python = %{version}-%{release}
Requires: PySocks
Requires: certifi
Requires: cryptography
Requires: idna
Requires: ipaddress
Requires: pyOpenSSL
BuildRequires : backports.ssl_match_hostname
BuildRequires : buildreq-distutils
BuildRequires : buildreq-distutils3
BuildRequires : certifi
BuildRequires : cffi
BuildRequires : cryptography
BuildRequires : mock
BuildRequires : ndg_httpsclient
BuildRequires : nose
BuildRequires : pbr
BuildRequires : pip
BuildRequires : pyOpenSSL
BuildRequires : pyasn1
BuildRequires : pycparser
BuildRequires : python-dev
BuildRequires : python-mock
BuildRequires : python3-dev
BuildRequires : setuptools
BuildRequires : setuptools-legacypython
BuildRequires : six
BuildRequires : tornado

%description
urllib3
=======
.. image:: https://travis-ci.org/urllib3/urllib3.svg?branch=master
:alt: Build status on Travis
:target: https://travis-ci.org/urllib3/urllib3

%package legacypython
Summary: legacypython components for the deprecated-urllib3 package.
Group: Default
Requires: python-core

%description legacypython
legacypython components for the deprecated-urllib3 package.


%package license
Summary: license components for the deprecated-urllib3 package.
Group: Default

%description license
license components for the deprecated-urllib3 package.


%package python
Summary: python components for the deprecated-urllib3 package.
Group: Default

%description python
python components for the deprecated-urllib3 package.


%prep
%setup -q -n urllib3-1.24.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1554329939
export MAKEFLAGS=%{?_smp_mflags}
python2 setup.py build -b py2

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/deprecated-urllib3
cp LICENSE.txt %{buildroot}/usr/share/package-licenses/deprecated-urllib3/LICENSE.txt
python2 -tt setup.py build -b py2 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files legacypython
%defattr(-,root,root,-)
/usr/lib/python2*/*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/deprecated-urllib3/LICENSE.txt

%files python
%defattr(-,root,root,-)
